 version: "3.9"
 
 services:
  trino:
    ports:
      - "8080:8080"
    image: "trinodb/trino"
    volumes:
      - ./docker/trino/etc:/usr/lib/trino/etc:ro
      - ./docker/trino/catalog:/etc/trino/catalog
     networks:
      - trino-network

  postgres:
    ports:
      - "5432:5432"
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
     networks:
      - trino-network

  minio:
    hostname: minio
 #  image: 'minio/minio:RELEASE.2022-05-26T05-48-41Z'
    image: minio/minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
     minio_storage: {}
#    - minio_storage:/data
    environment:
      MINIO_ACCESS_KEY: root
      MINIO_SECRET_KEY: minio123
#    command: server /data --console-address ":9001"
    command: server --console-address ":9001" /data

    depends_on:
      - minio

  networks:
   default:
    name: dbt-net
    external: true
    networks:
    
  trino-network:
    driver: bridge
